#!/bin/bash

#  Copyright 2013 Daniel Giribet <dani - calidos.cat>
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


# ZooKeeper
# 
# chkconfig: 2345 89 9 
# description: zookeeper init script

source /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0


retval_=0
mon_=${install.prefix_}/mon/bin/mon
mon_log_=/var/log/mon-zookeeper.log
pidfile_=/var/run/zookeeper.pid
monpid_=/var/run/mon-zookeeper.pid
desc_="ZooKeeper daemon"
lockfile_=/var/lock/subsys/zookeeper
zookeeper_="${zookeeper.installfolder_}/bin/zkServer.sh start"


source ${zookeeper.installfolder_}/bin/zkEnv.sh
export ZOO_LOG_DIR=

start() {
 	echo -n $"Starting $desc_ (zookeeper): "
	$mon_ -l "$mon_log_" -s 1  -p "$pidfile_" -m "$monpid_" -d "su - '${zookeeper.username_}' -m --session-command='sh $zookeeper_'"
  	retval_=$?
	echo
  	[ $retval_ -eq 0 ] && touch "$lockfile_"
    return $retval_
}

stop() {
 	echo -n $"Stopping ZooKeeper daemon (zookeeper): "
	kill -QUIT `cat "$monpid_"`
  	retval_=$?
  	sleep 5
  	echo
  	[ $retval_ -eq 0 ] && rm -f "$lockfile_" "$pidfile_" "$monpid_"
    return $retval_
}

restart() {
  stop
  start
}

checkstatus(){
	$mon_ -S --pidfile "$pidfile_"
	retval_=$?
}

condrestart(){
  [ -e "$lockfile" ] && restart || :
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    checkstatus
    ;;
  restart)
    restart
    ;;
  condrestart)
    condrestart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|condrestart}"
    exit 1
esac

exit $retval_
