#!/bin/bash

#  Copyright 2013 Daniel Giribet <dani - calidos.cat>
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


# ZooKeeper
# 
# chkconfig: 2345 89 9 
# description: zookeeper init script

source /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

source ${zookeeper.installfolder_}/bin/zkEnv.sh

RETVAL=0
PIDFILE="${ZOOPIDFILE}"
desc="ZooKeeper daemon"

lockfile=/var/lock/subsys/zookeeper

start() {
  echo -n $"Starting ZooKeeper daemon (zookeeper): "

  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch "$lockfile"
  return $RETVAL
}

stop() {
  echo -n $"Stopping ZooKeeper daemon (zookeeper): "

  RETVAL=$?
  sleep 5
  echo
  [ $RETVAL -eq 0 ] && rm -f "$lockfile" $PIDFILE
}

restart() {
  stop
  start
}

checkstatus(){

  RETVAL=$?
}

condrestart(){
  [ -e "$lockfile" ] && restart || :
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    checkstatus
    ;;
  restart)
    restart
    ;;
  condrestart)
    condrestart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|condrestart}"
    exit 1
esac

exit $RETVAL
